### ISSUE TITLE
List users and the assigned products

### ISSUE THREAD

**Issue by kim-ras** [adobe-apiplatform/umapi-documentation#26]
For a Software Asset Management project am I am trying to extract the data around the Enterprise agreement: 
Agreement number(s), the Users and what products that are allowed to use.
Also a indicator of the last usage would be awesome.

I can get a list of users.. but the rest I am struggling to retrieve..

Thanks in advance
Kim

**Comment by adobeDan** [comment]
Sorry, Kim, but none of that info is available via UMAPI.
