### ISSUE TITLE
No documentation for "error.unauthorized"

### ISSUE THREAD

**Issue by adorton-adobe** [adobe-apiplatform/umapi-documentation#31]
I'm working with a customer who is getting the error code "error.unauthorized" with the message "failed to authenticate provided token".  I don't see this error on the error documentation page.

**Comment by lesavage** [comment]
This error is returned prior to UMAPI being invoked and is due to the authentication token being invalid: https://adobe-apiplatform.github.io/umapi-documentation/en/UM_Authentication.html
