### ISSUE TITLE
Depreciation of 'Get All Users in Organization'

### ISSUE THREAD

**Issue by SmithPlatts** [adobe-apiplatform/umapi-documentation#41]
The `getUsersREST` page documents that this mechanism will be depreciated, yet there is no known date, and no documented API alternate to get the Adobe ID of a user.

What is the state of this API?

**Comment by lesavage** [comment]
The alternative APIs are:
Get a single user: https://adobe-apiplatform.github.io/umapi-documentation/en/api/getUser.html
Get Users: https://adobe-apiplatform.github.io/umapi-documentation/en/api/getUsersWithPage.html

The getUsersREST API is still available but not actively maintained.
