### ISSUE TITLE
UMAPI and its interaction when syncing to a local AD

### ISSUE THREAD

**Issue by honungsburk** [adobe-apiplatform/umapi-documentation#45]
Playing around with the API for a bit I've noticed that it doesn't behave as I would expect in an environment where the local AD is synced to Adobe. 

1. querying "GET /v2/usermanagement/groups/{orgId}/{page}" sometimes returns groups that are missing which type it is
2. querying "GET /v2/usermanagement/groups/{orgId}/{page}" will not return all groups!
3. querying "GET /v2/usermanagement/organizations/{orgId}/users/{userString}" you find that users beloning to groups not returned by "GET /v2/usermanagement/groups/{orgId}/{page}",
4. even when Adobe is not synched to the local AD the endpoint "GET /v2/usermanagement/organizations/{orgId}/users/{userString}" won't tell you if a user belongs to the SYS_ADMIN_GROUP with the name "Admin"

From a consumer perspective, the best option would be if these issues didn't exist in the first place but I realize that there might be limitations to what is possible.

**Comment by Luci2015** [comment]
I would suggest to open a support ticket with Adobe so that all these issues be approached one by one, with sample calls and server replies.
These would be some serious bugs if proven.

**Comment by honungsburk** [comment]
I've done as you suggested and opened a support ticket with Adobe.
