### ISSUE TITLE
. dot is interpreted as special character and cuts off the group string

### ISSUE THREAD

**Issue by oakimov** [adobe-apiplatform/umapi-documentation#53]
When a group name contains a dot and a space, i.e. 'my group name company co. ltd. product', it appears that the dot is interpreted by the API as a special symbol and the remainder of the string is cut off.
i.e. I am trying to pull data for 
https://usermanagement.adobe.io/v2/usermanagement/users/org_id@AdobeOrg/0/my group name company co. ltd. product

getting the following result:
{
    "lastPage": false,
    "result": "error.group.not_found",
    "message": "Not found: my group name company co. ltd"
}

Although group with name 'my group name company co. ltd. product' definetely exists

What would be the escape character . (dot) can be escaped with?

**Comment by Luci2015** [comment]
I did not test yet, but maybe if you URL encode the group name before using it after the /page/ might solve it.
Oherwise you can also try with this format:
 `/v2/usermanagement/users/{orgId}/{page}/{groupId}`

groupId can be obtained in the reply of getting all groups from the Org:
`GET /v2/usermanagement/groups/{orgId}/{page}`

**Comment by oakimov** [comment]
The issue is occuring in the same way also when URL is encoded, i.e. as
my%20group%20name%20company%20co.%20ltd.%20product
the API still provides the same response.

The workaround with the groupId works.

**Comment by Luci2015** [comment]
alternatively  the group in Admin Console could be renamed if it is not creating a problem elsewhere..

**Comment by oakimov** [comment]
Is there an escape character dot can be escaped with?

**Comment by Luci2015** [comment]
not at this time;
at most you can replace it in the source (admin console group name) with some other char, like - or _
