### ISSUE TITLE
removeFromOrg Giving Error

### ISSUE THREAD

**Issue by lsimon17** [adobe-apiplatform/umapi-documentation#60]
Hi there, we are testing around with the API trying to remove user accounts and are having difficulties doing so.
```
url = "https://" + host + endpoint + "/action/" + org_id
headers = {
    "Content-type" : "application/json",
    "Accept" : "application/json",
    "x-api-key" : api_key,
    "Authorization" : "Bearer " + access_token
    }

json_data = \
[{
  "user": "user@" + domain,
  "requestID": "action_1",
  "do": [{
    "removeFromOrg": {
      "deleteAccount": False
    }
  }]
}]

# prepare body
body = json.dumps(json_data)
print("Sending following request body to User Management Action API: " + body +"\n")

# send http request
http = urllib3.PoolManager()
res = http.request('POST', url, headers=headers, body=body)

print(res.data)
```

We've tried switching to 'True' and 'False' in the deleteAccount field, but it produces the same error

The error: 
`b'{"completed":0,"notCompleted":1,"completedInTestMode":0,"result":"error","errors":[{"index":0,"step":0,"message":"Error removing user from organization: FAILURE","errorCode":"error.internal.removefromorg","requestID":"action_1","user":"user@domain.com"}]}'`

**Comment by adorton-adobe** [comment]
On your action payload, are you passing the user's email or username here?

```
"user": "user@" + domain,
```

You should be passing the user's email address and not username.

Your sample also appears to be Python. If so, you should take a look here: https://github.com/adobe-apiplatform/umapi-client.py/
