### ISSUE TITLE
Multiple Analytics Login Companies within an IMS Org creates ambiguously named _product_admin groups

### ISSUE THREAD

**Issue by optumgadell** [adobe-apiplatform/umapi-documentation#66]
We have two Analytics Login Companies within the same IMS Org [8E391C8B533058250A490D4D@AdobeOrg]. This results in two identically named _product_admin_ groups with different groupIds (which can be found by dumping all of the groups with Postman connecting to UMAPI):

{
"groupId": 8466089,
"groupName": "_product_admin_Adobe Analytics",
"type": "PRODUCT_ADMIN_GROUP",
"memberCount": 50,
"productName": "Adobe Analytics"
}

{
"groupId": 34878106,
"groupName": "_product_admin_Adobe Analytics",
"type": "PRODUCT_ADMIN_GROUP",
"memberCount": 12,
"productName": "Adobe Analytics"
}

UMAPI will return the correct user list if I pass it the groupId (instead of name), like:
https://{{UMAPI_ENDPOINT}}/v2/usermanagement/users/{{UMAPI_IMS_ORG}}/{{UMAPI_PAGE}}/34878106

However there doesn't seem to be a way to specify which group to target when attempting to add a user to the group. (UMAPI only accepts groupName.)

**Comment by lesavage** [comment]
This is currently being investigated.

**Comment by lesavage** [comment]
Additional metadata has been added to product names to help differentiate them.
